# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "215e05e29fa6942094adfd105b2b0905"
name = "bundle-builder-26"
application_url = "https://build-your-own-bundle.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_products,write_app_proxy"

[auth]
redirect_urls = [ "https://build-your-own-bundle.fly.dev/auth/callback" ]

[app_proxy]
url = "/apps/bundle-builder-1"
prefix = "apps"
subpath = "bundle-builder-1"
